name: snakemake-mapping
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bedtools
  - bowtie2
  - fastp
  - samtools
  - snakemake-minimal=5.4.5
  - pip:
    - biopython==1.72
    - fastools==1.0.1
    - pysam


