name: snakemake-mapping
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - appdirs=1.4.3
  - attrs=19.3.0
  - bcftools=1.9
  - bwa=0.7.17
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - certifi=2019.11.28
  - cffi=1.13.2
  - chardet=3.0.4
  - configargparse=0.13.0
  - cryptography=2.8
  - curl=7.65.3
  - cycler=0.10.0
  - datrie=0.8
  - dbus=1.13.6
  - decorator=4.4.1
  - docutils=0.15.2
  - expat=2.2.5
  - fontconfig=2.13.1
  - freetype=2.10.0
  - gettext=0.19.8.1
  - gitdb2=2.0.6
  - gitpython=3.0.5
  - glib=2.58.3
  - graphite2=1.3.13
  - graphviz=2.38.0
  - gsl=2.5
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - harfbuzz=2.4.0
  - htslib=1.9
  - icu=58.2
  - importlib_metadata=1.2.0
  - jinja2=2.10.3
  - jpeg=9c
  - jsonschema=3.2.0
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.65.3
  - libdeflate=1.2
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - matplotlib=2.2.3
  - matplotlib-base=2.2.3
  - more-itertools=8.0.2
  - ncurses=6.1
  - networkx=2.1
  - numpy=1.17.3
  - openssl=1.1.1d
  - pango=1.40.14
  - pcre=8.43
  - perl=5.26.2
  - pip=19.3.1
  - pixman=0.38.0
  - psutil=5.6.7
  - pthread-stubs=0.4
  - pycparser=2.19
  - pyopenssl=19.1.0
  - pyparsing=2.4.5
  - pyqt=5.6.0
  - pyrsistent=0.15.6
  - pysam=0.15.0.1
  - pysocks=1.7.1
  - python=3.6.7
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyyaml=5.2
  - qt=5.6.3
  - ratelimiter=1.2.0
  - readline=8.0
  - samtools=1.9
  - setuptools=42.0.2
  - sip=4.18.1
  - six=1.13.0
  - smmap2=2.0.5
  - snakemake-minimal=5.4.5
  - sqlite=3.30.1
  - tk=8.6.10
  - tornado=6.0.3
  - wheel=0.33.6
  - wrapt=1.11.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxpm=3.5.12
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.2.2
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - biopython==1.72
    - configparser==3.5.0
    - demultiplex==1.1.0
    - dict-trie==1.0.1
    - fastools==1.0.1
    - idna==2.7
    - jit-open==0.0.4
    - python-levenshtein==0.12.0
    - requests==2.19.1
    - tssv==1.0.3
    - urllib3==1.23

